### ISSUE TITLE
(DD) DoWhileRatherThanWhileRefactoring - MalformedTreeException

### ISSUE THREAD

**Issue by cal101** [JnRouvignac/AutoRefactor#292] opened 2017-08-03 10:15 UTC
MalformedTreeException: Range of child edit lies outside of parent edit

With help of improved delta debugging #286 can be further analyzed.

Based on https://git.eclipse.org/c/jdt/eclipse.jdt.core.git/tree/org.eclipse.jdt.core/compiler/org/eclipse/jdt/core/compiler/CharOperation.java

The code
```
import java.util.Arrays;
import org.eclipse.jdt.internal.compiler.parser.ScannerHelper;
public final class CharOperation {
public static final boolean camelCaseMatch(char[] pattern, int patternStart, int patternEnd, char[] name, int nameStart, int nameEnd, boolean samePartCount) {
	char patternChar, nameChar;
	int iName = nameStart;
	do {
		while (true) {
			nameChar = name[iName];
			if (nameChar < ScannerHelper.MAX_OBVIOUS) {
			}
		}
		// Since pattern is also at an uppercase letter
	} while (true);
}
public static final int hashCode(char[] array) {
	int hash = Arrays.hashCode(array);
	return hash & 0x7FFFFFFF;
}
public static final String[] toStrings(char[][] array) {
	int length = array.length;
	String[] result = new String[length];
	return result;
}
}
```

result in

```
org.autorefactor.util.IllegalStateException: CharOperation.java:1:1:Illegal changes have been created by org.autorefactor.refactoring.rules.SimplifyExpressionRefactoring, org.autorefactor.refactoring.rules.AddBracketsToControlStatementRefactoring, org.autorefactor.refactoring.rules.RemoveEmptyLinesRefactoring, org.autorefactor.refactoring.rules.PushNegationDownRefactoring, org.autorefactor.refactoring.rules.DoWhileRatherThanWhileRefactoring for file CharOperation.java. (Range of child edit lies outside of parent edit) Parent text edit: {DeleteEdit} [23537,1227]
  {CopySourceEdit} [23544,4], child text edit: {CopySourceEdit} [23550,1349]
```

**Comment by Fabrice-TIERCELIN** [comment] 2017-08-03 20:43
This is due to the comment after the while loop without following statement. JDT is lost for the location of the end of the statement. This is closely related to #181.

We will look for a solution.

**Comment by Fabrice-TIERCELIN** [comment] 2017-08-08 19:28
Duplicate of #291.

**Closed by Fabrice-TIERCELIN** 2017-08-08 19:28 UTC
Labels: duplicate
