### ISSUE TITLE
ReduceVariableScope sample output currently appears not refactored?

### ISSUE THREAD

**Issue by twhitmorenz** [JnRouvignac/AutoRefactor#122] opened 2015-05-04 23:21 UTC
Hi Jean-Noël,

I'm looking at your AutoRefactor plugin and very interested in the "reduce variable scopes" factoring -- but notice that the current samples don't appear to show it working.

I'm interested to try reducing variable scopes in an automatic way, as I have a large codebase suffering from this problem. Also interested by your latest work moving to a full CFG!

Regards,
Thomas Whitmore
Bravura Solutions

**Comment by JnRouvignac** [comment] 2015-05-05 06:52
Hi Thomas,

The samples are ready, but this is not working yet. You can follow issue #7 to track progress (I have not started yet).
I first need to implement the CFG as described in issue #93 .
Thanks for expressing your interest.

I am closing this issue as a duplicate of #7.

**Closed by JnRouvignac** 2015-05-05 06:52 UTC

**Comment by JnRouvignac** [comment] 2015-05-05 09:02
Consider joining the discussion on gitter (see the badge on the first page)

**Comment by twhitmorenz** [comment] 2015-05-06 03:18
Thanks Jean-Noël.
