### ISSUE TITLE
Texts are missing on "Choose refactoring..." panel

### ISSUE THREAD

**Issue by Wawet76** [JnRouvignac/AutoRefactor#133] opened 2015-06-10 09:14 UTC
Labels are obviously missing.

![autorefactor](https://cloud.githubusercontent.com/assets/1931861/8078916/4593f50c-0f61-11e5-9321-797867590a2e.png)

Eclipse Version: Luna Service Release 2 (4.4.2)
Windows 7
Autorefactor stable release

**Comment by JnRouvignac** [comment] 2015-06-10 09:17
Thanks for the bug report.
Strange. What version of AutoRefactor are you using?

**Comment by Wawet76** [comment] 2015-06-10 09:18
1.0.0

**Comment by JnRouvignac** [comment] 2015-06-10 09:22
Do you mind uninstanlling the released version, then try with the nightly?
update site for the nightly is http://autorefactor.org/nightly/

I will do some testing myself once I will have some time available.

**Comment by Wawet76** [comment] 2015-06-10 09:27
I tried to use the "normal" Windows 7 theme, and the bug disappear.

Problem only occurs with "Windows Classic" theme selected. (The rest of Eclipse is working without problem)

**Comment by JnRouvignac** [comment] 2015-06-10 09:31
That's useful info. Thanks again.

This dialog page uses a `StyledCellLabelProvider` with `StyledString`.
I wonder if this could cause the issue with this theme?
I still need to figure out if the problem is in AutoRefactor code or in the Eclipse theme (So far I am leaning towards this)

**Comment by Wawet76** [comment] 2015-06-10 09:41
Changing the Eclipse Theme has no effect. This bug only appears with the Windows theme "classic" that make all Windows 7 looks like 98/2000.

I agree that it seems like an Eclipse/Windows bug, not specific to Autorefactor.

(Same problem with 1.1.0.201506062344)

**Comment by JnRouvignac** [comment] 2015-06-10 09:44
Sorry I misread then, this is when you are switching the theme on windows itself?
OK, then if you agree, I think I am going to close it as "not a bug in AutoRefactor"

Thank you so much for your time in helping diagnosing the issue.
Now I'll know what to answer to similar bug reports in the future.

**Closed** 2015-06-10 09:45 UTC
Labels: bug
