### ISSUE TITLE
Definition of Bug

### ISSUE THREAD

**Issue by cal101** [JnRouvignac/AutoRefactor#157] opened 2016-02-29 16:01 UTC
Hi!

I am trying AutoRefactor on source code having a long history and I am using brute force style:
    Applying all refactorings and see what happens.

Is the following correct for all instances of AllRefactoringRules.getAllRefactoringRules() or 
are their exceptions?

If the refactoring produces code that can't be compiled that is a bug.
If the refactoring changes the semantics that is a bug.

Cal

P.S.
    I sent you an email to discuss findings and how to bulk report problems.

**Comment by JnRouvignac** [comment] 2016-02-29 17:32
Yes these are the general rules. There are very few places where behaviour is changed (otherwise it would not be possible to do as many things as are done today), hence why a developer should always review the changes before committing them.

I would suggest you refactor code rule by rule m, otherwise you will be overwhelmed by the number of changes.
See "best practices" section in http://autorefactor.org

If you are in doubt then plaise raise an issue and let's have the discussion there.

Thanks Cal

**Comment by cal101** [comment] 2016-02-29 17:50
Sure. 
For real appliance I would do it refactoring by refactoring and do a manual review + test execution.
For that to be possible it's important that whitespace changes are kept small and that is the case. 
Great!

I just wanted to know what base line you set for accepted behavior.

Is there some list of semantic changes you expect/know to happen?
I don't count "loop/equals -> contains" as a (real) semantic change.

And I wanted to know the overall robustness and exactness of the refactorings so
I used the "all refactoring to all code" approach.

I run it against 23000 classes and got

- 130 compile failures
- >=35 infinite loops
- >=3 "Code is not implemented for extended operands" - so the case seems to happen
- >=10 "Overlapping text edits"
-  NPE/AIOOB/IAE exceptions

The question is how to priorize.

Cal

**Comment by cal101** [comment] 2016-02-29 17:56
I like this one:

Why may the following be NO DEAD CODE?


@Override
    protected void setUp() throws Exception {
        super.setUp();
    }

.
.
.
 Because the CALL to this setUp method may be done by another class  THE SAME PACKAGE
which has not necessarily access to the package where the super class resides and so has
no access to the setUp method.

**Comment by JnRouvignac** [comment] 2016-02-29 18:42
Wow! This is certainly not my experience!

Here is how I would prioritize:

# 130 compile failures
# 35 infinite loops
# >=10 "Overlapping text edits"
# NPE/AIOOB/IAE exceptions
# >=3 "Code is not implemented for extended operands" - so the case seems to happen

**Comment by JnRouvignac** [comment] 2016-02-29 19:06
Is the overriden method a problem you encountered?

**Comment by cal101** [comment] 2016-02-29 19:14
Yes I found the overridden case in our code base. This looks like a JUnit setUp but is a part used in some test case that just gets initialized this way in the test case setup.

A small robustness issue: 
I forgot to set a classpath library variable and so my class path was incomplete.
That means "IAnnotationBinding annotationBinding = node.resolveAnnotationBinding();" in AnnotationRefactoring returned null and that gave an NPE in next line.

**Comment by cal101** [comment] 2016-02-29 19:36
You asked for the version: 
commit b9306ce5199fb81a067e498f4cd2b0705bb028ea

**Comment by cal101** [comment] 2016-02-29 19:48
For locating the compile errors I would like JDT to parse/compile my code. 
And give me immediate feedback if the refactoring broke the code.

I am currently using
```
			IPackageFragment pf = pfr.getPackageFragment(packageName(relativePath(sourceFolder, resource)));
			ICompilationUnit cu = pf.getCompilationUnit(name);
			final IDocument doc = new Document(readFileToString(resource.getLocation().toFile().getAbsolutePath()));
			new ApplyRefactoringsJob(null, null).applyRefactoring(
					doc, cu,
					new AggregateASTVisitor(AllRefactoringRules.getAllRefactoringRules()),
					newJavaProjectOptions(Release.javaSE("1.7.0"), 4));
```
to call the refactoring on some java code.
Do you know how can I get jdt to parse/validate the changed source code?

**Comment by JnRouvignac** [comment] 2016-02-29 19:49
I am disappointed :-/
This was supposed to be the base for the long overdue version 1.1.0. 
So I am even more interested in any bug reports you can provide.

Thanks for the report on `resolveAnnotationBinding()`.
I keep forgetting null checks on `resolve*()` methods.

**Comment by cal101** [comment] 2016-02-29 19:57
I can't say how many things are known problems or duplicates.
For example I saw a lot of wrong refactorings of "<XXX>" to "<>".
I commented on that issue in the email I sent.

The code base I tested it on is not small and has code from java 1.2 to java 1.7.
Different idioms and styles. 
I understand your disappointment but hey, let's have some fun and let us fix it.
I just fear that I would have enough todo to just identify and report instead of fixing.

**Comment by cal101** [comment] 2016-02-29 20:33
Oh, i forgot that you may not be able to identify my email. Title contains "Triage"

**Comment by JnRouvignac** [comment] 2016-02-29 21:52
> The code base I tested it on is not small and has code from java 1.2 to java 1.7.

Same for the code bases I am testing AutoRefactor on (Although it might have started with Java 1.4), but I did not encounter the same issues as you.

> I understand your disappointment but hey, let's have some fun and let us fix it.
Don't worry, this is a temporary deception. I am actually very happy when somebody reports an issue. I can then fix it and ignore it later on.

> I just fear that I would have enough todo to just identify and report instead of fixing.

Identifying the issue is half the bug fixed
I need identification of the culprit code so I can add non unit tests that will help  me fix the bug faster (no need to fire up a whole Eclipse) and will prevent regressions.

**Comment by JnRouvignac** [comment] 2016-02-29 22:05
> Do you know how can I get jdt to parse/validate the changed source code?

I think I saw an API but I have not been able to find it again for the moment.

**Comment by JnRouvignac** [comment] 2016-02-29 22:12
Found it:

```java
CompilationUnit unit = (CompilationUnit) parser.createAST(null);
IProblem[] pbs = unit.getProblems();
```

**Comment by cal101** [comment] 2016-02-29 22:35
Cool, thanks. That calls for some bi-secting of the refactorings list tomorrow after work.

**Comment by cal101** [comment] 2016-03-01 16:41
I created bug tickets for all Refactorings they lead to uncompilable code.

After disabling all those refactorings the code is compilable per definition. ;-)

**Comment by JnRouvignac** [comment] 2016-03-01 19:49
Thank you so much for providing all this feedback!

To debug infinite loops, put a breakpoint here: https://github.com/JnRouvignac/AutoRefactor/blob/master/plugin/src/main/java/org/autorefactor/ui/ApplyRefactoringsJob.java#L215 at line 215 and see which refactoring rules are still running.

**Comment by JnRouvignac** [comment] 2016-03-31 20:11
I am closing this now. I think I have answered or created issues based on this conversation.

**Closed by JnRouvignac** 2016-03-31 20:11 UTC
